
ifneq ("gfortran","$(strip $(FC))")
$(error "Ignoring fortraninterface for Windows (only FC=gfortran is supported).")
endif

# Windows
LIBS		= ../lowlevel/libal.lib
LIBS		+= -lm -lstdc++
JAVA		= $(JAVA_HOME)/bin/java

ifeq ("yes","$(strip $(IMAS_MDSPLUS))")
LIBS	+= -L$(MDSPLUS_DIR)/lib
LIBS	+= $(MDSPLUS_DIR)/lib/XTreeShr.a
LIBS	+= $(MDSPLUS_DIR)/lib/MdsObjectsCppShr.a
LIBS	+= $(MDSPLUS_DIR)/lib/TdiShr.a
LIBS	+= $(MDSPLUS_DIR)/lib/TreeShr.a
LIBS	+= $(MDSPLUS_DIR)/lib/MdsIpShr.a
LIBS	+= $(MDSPLUS_DIR)/lib/MdsShr.a
LIBS	+= -lxml2 -lws2_32 -ldl -liphlpapi -lstdc++
endif

ifeq ("yes","$(strip $(IMAS_UDA))")
ifeq ("yes","$(strip $(IMAS_UDAFAT))")
LIBS	+= -L$(UDA_HOME)/lib
LIBS	+= $(UDA_HOME)/lib/libfatuda_cpp.a
LIBS	+= $(UDA_HOME)/lib/libportablexdr.a
LIBS	+= $(PostgresSQL_ROOT)/lib/libpq.a
LIBS	+= -lws2_32 -lssl -lcrypto -lstdc++ -lxml2
else
LIBS	+= -L$(UDA_HOME)/lib
LIBS	+= $(UDA_HOME)/lib/libuda_cpp.a
LIBS	+= $(UDA_HOME)/lib/libportablexdr.a
LIBS	+= -lws2_32 -lssl -lcrypto -lstdc++
endif
endif
 
ifeq ("yes","$(strip $(IMAS_HDF5))")
LIBS	+= -L$(HDF5_HOME)/lib
LIBS	+= $(HDF5_HOME)/lib/libhdf5.a -ldl -lz -lstdc++
endif

ifeq ("gfortran","$(strip $(FC))")
TARGETS += libal-fortran.dll libal-fortran.lib
TARGETS += id_fortran_all
INSTALL_TARGETS += fortran_install id_fortran_install
IDSOBJECTS=$(addsuffix .o,$(IDSNAMES_FUNC))
endif
