LIBS		= -L../lowlevel -lal -lm

ifneq ("no","$(strip $(IMAS_FORTRAN))")
TARGETS += libal-fortran.so libal-fortran.a
TARGETS += id_fortran_all
PC_FILES += al-fortran.pc
PC_FILES_VAR += al-fortran-$(DD_GIT_DESCRIBE).pc
PC_FILES_ALT += $(ID_fortran_PC_FILES_2)
INSTALL_TARGETS += fortran_install id_fortran_install
IDSOBJECTS=$(addsuffix .o,$(IDSNAMES_FUNC))
endif

