#include ../Makefile.common

TARGETS= TestSuite bla

F90_gfortran=gfortran
COPTS_gfortran = -g -fdefault-real-8 -fPIC -fno-second-underscore -ffree-line-length-none $(shell eval-pkg-config --cflags ual-gfortran) 
LIBS_gfortran=$(shell eval-pkg-config --libs ual-gfortran) -lm

CPODEF= $(UAL)/xml/CPODef.xml

all : setup
	
clean:
	rm -rf build *~ *.o *.mod
	
clean-src: clean
	rm -f *.o

install: all
	
setup: TestSuiteFortran.xsl  
	xsltproc TestSuiteFortran.xsl $(CPODEF)  > bla.f90




comp: $(TARGETS)


#--------------------- gfortran ------------------------

TestSuite: TestSuite.f90
	$(F90_gfortran) $(COPTS_gfortran)   -c $^ $(LIBS_gfortran)
	

bla: bla.f90 TestSuite.o
	$(F90_gfortran) $(COPTS_gfortran)   -o $@ $^ $(LIBS_gfortran)


	

