
# Please do not run make on this file directly.
ifeq (1,$(words $(MAKEFILE_LIST)))
  $(error Do not run make on this file directly, use Makefile or Makefile-local)
endif

# Require explicit target, do not assume make all
help:
	$(error Specify a target to run, e.g. make test.)


	
# Make NEW_LOW_LEVEL=yes default
NEW_LOW_LEVEL?=yes

IFORT_BIN_DIR:=./bin/ifort
IFORT_BUILD_DIR:=./build/ifort
GFORTRAN_BIN_DIR:=./bin/gfortran
GFORTRAN_BUILD_DIR:=./build/gfortran
TEST_SRC_DIR=./src
TMP_DIR=./tmp

ifneq ("no","$(strip $(IMAS_GFORTRAN))")
  TARGETS += $(GFORTRAN_BIN_FILES) $(GFORTRAN_BIN_FILES_PUT) $(GFORTRAN_BIN_FILES_GET)
  TESTS += $(GFORTRAN_TESTS)
  COPTS_gfortran+=-J$(GFORTRAN_BUILD_DIR)
endif

ifneq ("no","$(strip $(IMAS_IFORT))")
  TARGETS += $(IFORT_BIN_FILES) $(IFORT_BIN_FILES_PUT) $(IFORT_BIN_FILES_GET)
  TESTS += $(IFORT_TESTS)
  COPTS_ifort+=-module $(IFORT_BUILD_DIR)
endif

# Get a list of IDS from IDSDEF file
IDSNAMES := $(shell sed '/<IDS name=/!d;s/.*name="\([^"]*\)".*/\1/' $(IDSDEF))
TEST_IDS_FILES = $(patsubst %,$(TEST_SRC_DIR)/%_all_test.f90,$(IDSNAMES))
IDS_SOURCES = $(patsubst %,$(TEST_SRC_DIR)/%_test.f90,$(IDSNAMES))
IDS_SOURCES += $(patsubst %,$(TEST_SRC_DIR)/%_test_dynamic.f90,$(IDSNAMES))
IDS_SOURCES += $(patsubst %,$(TEST_SRC_DIR)/%_test_static.f90,$(IDSNAMES))
IDS_SOURCES += $(patsubst %,$(TEST_SRC_DIR)/%_init_dynamic.f90,$(IDSNAMES))
IDS_SOURCES += $(patsubst %,$(TEST_SRC_DIR)/%_init_static.f90,$(IDSNAMES))
TEST_IDS_FILES_PUT = $(patsubst %,$(TEST_SRC_DIR)/%_put_test.f90,$(IDSNAMES))
TEST_IDS_FILES_GET = $(patsubst %,$(TEST_SRC_DIR)/%_get_test.f90,$(IDSNAMES))
IDS_SOURCES += $(TEST_IDS_FILES_PUT) $(TEST_IDS_FILES_GET)

IFORT_BIN_FILES=$(patsubst %.f90,$(IFORT_BIN_DIR)/%.exe,$(notdir $(TEST_IDS_FILES)))
IFORT_BIN_FILES_PUT=$(patsubst %.f90,$(IFORT_BIN_DIR)/%.exe,$(notdir $(TEST_IDS_FILES_PUT)))
IFORT_BIN_FILES_GET=$(patsubst %.f90,$(IFORT_BIN_DIR)/%.exe,$(notdir $(TEST_IDS_FILES_GET)))

GFORTRAN_BIN_FILES=$(patsubst %.f90,$(GFORTRAN_BIN_DIR)/%.exe,$(notdir $(TEST_IDS_FILES)))
GFORTRAN_BIN_FILES_PUT=$(patsubst %.f90,$(GFORTRAN_BIN_DIR)/%.exe,$(notdir $(TEST_IDS_FILES_PUT)))
GFORTRAN_BIN_FILES_GET=$(patsubst %.f90,$(GFORTRAN_BIN_DIR)/%.exe,$(notdir $(TEST_IDS_FILES_GET)))


GFORTRAN_TESTS = gfortran_initpulse_test gfortran_test
IFORT_TESTS = ifort_initpulse_test ifort_test

all: $(TARGETS)
check test: $(TESTS)
sources: $(IDS_SOURCES)
#sources2: $(IDS_SOURCES) $(IDS_SOURCES2)

# Create src and bin dirs as needed
$(TEST_SRC_DIR) $(IFORT_BIN_DIR) $(GFORTRAN_BIN_DIR) $(IFORT_BUILD_DIR) $(GFORTRAN_BUILD_DIR) $(TMP_DIR):
	$(mkdir_p) $@

.PHONY: clean clean-src
clean: ifort_clean gfortran_clean
	$(RM) -r idspath-*
	$(RM) -r *.log

clean-src: clean
	$(RM) -r $(TEST_SRC_DIR)


#################################################
#                 INIT: SOURCE GENERATION
#################################################
# Test if all generated sources are found to exist as files and
# gracefully skip generation if not needed.
ifeq ($(words $(IDS_SOURCES)), $(words $(wildcard $(IDS_SOURCES))))
$(IDS_SOURCES):
else
$(IDS_SOURCES): sources_
endif
ifeq ($(words $(IDS_SOURCES2)), $(words $(wildcard $(IDS_SOURCES2))))
$(IDS_SOURCES2):
else
$(IDS_SOURCES2): sources2_
endif

# Target sources is reserved (used by user to build sources only)
# Need a single target to prevent parallel building:
sources_: IDSDef2TestSuite.xsl $(IDSDEF) | saxonicajar $(TEST_SRC_DIR)
	java net.sf.saxon.Transform newLowLevel=$(NEW_LOW_LEVEL) -t -s:$(IDSDEF) -xsl:IDSDef2TestSuite.xsl

sources2_: IDSDef2TestSuite.xsl $(IDSDEF) | saxonicajar $(TEST_SRC_DIR)
	java net.sf.saxon.Transform newLowLevel=$(NEW_LOW_LEVEL) sources2="yes" -t -s:$(IDSDEF) -xsl:IDSDef2TestSuite.xsl

#################################################
#              BUILD
#################################################

#------------------------- gfortran ----------------------------
.PHONY: gfortran_clean
gfortran_clean:
	$(RM) -r $(GFORTRAN_BIN_DIR)
	$(RM) -r $(GFORTRAN_BUILD_DIR)
	$(RM) gfortran_initpulse
	
$(GFORTRAN_BUILD_DIR)/generator.o: $(GFORTRAN_BUILD_DIR)/%.o: %.f90 | $(GFORTRAN_BUILD_DIR)
	$(FC_gfortran) $(COPTS_gfortran) -c $< -o $@

$(GFORTRAN_BUILD_DIR)/helper.o \
$(GFORTRAN_BUILD_DIR)/setter.o \
$(GFORTRAN_BUILD_DIR)/comparator.o: $(GFORTRAN_BUILD_DIR)/%.o: %.f90 $(GFORTRAN_BUILD_DIR)/generator.o
	$(FC_gfortran) $(COPTS_gfortran) -c $< -o $@
	
$(GFORTRAN_BUILD_DIR)/%_init_static.o: $(TEST_SRC_DIR)/%_init_static.f90 $(GFORTRAN_BUILD_DIR)/setter.o
	$(FC_gfortran) $(COPTS_gfortran) -c $< -o $@
	
$(GFORTRAN_BUILD_DIR)/%_init_dynamic.o: $(TEST_SRC_DIR)/%_init_dynamic.f90 $(GFORTRAN_BUILD_DIR)/setter.o
	$(FC_gfortran) $(COPTS_gfortran) -c $< -o $@
	
$(GFORTRAN_BUILD_DIR)/%_test_static.o: $(TEST_SRC_DIR)/%_test_static.f90 $(GFORTRAN_BUILD_DIR)/comparator.o
	$(FC_gfortran) $(COPTS_gfortran) -c $< -o $@

$(GFORTRAN_BUILD_DIR)/%_test_dynamic.o: $(TEST_SRC_DIR)/%_test_dynamic.f90 $(GFORTRAN_BUILD_DIR)/comparator.o  
	$(FC_gfortran) $(COPTS_gfortran) -c $< -o $@

$(GFORTRAN_BUILD_DIR)/%_test.o: $(TEST_SRC_DIR)/%_all_test.f90 $(GFORTRAN_BUILD_DIR)/helper.o $(GFORTRAN_BUILD_DIR)/%_init_static.o $(GFORTRAN_BUILD_DIR)/%_init_dynamic.o $(GFORTRAN_BUILD_DIR)/%_test_static.o $(GFORTRAN_BUILD_DIR)/%_test_dynamic.o
	$(FC_gfortran) $(COPTS_gfortran) -c $< -o $@
	
$(GFORTRAN_BIN_FILES): $(GFORTRAN_BIN_DIR)/%_all_test.exe: $(GFORTRAN_BUILD_DIR)/setter.o $(GFORTRAN_BUILD_DIR)/comparator.o $(GFORTRAN_BUILD_DIR)/generator.o $(GFORTRAN_BUILD_DIR)/helper.o $(GFORTRAN_BUILD_DIR)/%_test.o $(GFORTRAN_BUILD_DIR)/%_init_static.o $(GFORTRAN_BUILD_DIR)/%_init_dynamic.o $(GFORTRAN_BUILD_DIR)/%_test_static.o $(GFORTRAN_BUILD_DIR)/%_test_dynamic.o | $(GFORTRAN_BIN_DIR)
	$(FC_gfortran) $(COPTS_gfortran) -o $@ $^ $(LIBS_gfortran)
	
#-------------

$(GFORTRAN_BUILD_DIR)/%_put_test.o: $(TEST_SRC_DIR)/%_put_test.f90 $(GFORTRAN_BUILD_DIR)/helper.o $(GFORTRAN_BUILD_DIR)/%_init_static.o $(GFORTRAN_BUILD_DIR)/%_init_dynamic.o $(GFORTRAN_BUILD_DIR)/%_test_static.o $(GFORTRAN_BUILD_DIR)/%_test_dynamic.o
	$(FC_gfortran) $(COPTS_gfortran) -c $< -o $@

$(GFORTRAN_BUILD_DIR)/%_get_test.o: $(TEST_SRC_DIR)/%_get_test.f90 $(GFORTRAN_BUILD_DIR)/helper.o $(GFORTRAN_BUILD_DIR)/%_init_static.o $(GFORTRAN_BUILD_DIR)/%_init_dynamic.o $(GFORTRAN_BUILD_DIR)/%_test_static.o $(GFORTRAN_BUILD_DIR)/%_test_dynamic.o
	$(FC_gfortran) $(COPTS_gfortran) -c $< -o $@

$(GFORTRAN_BIN_FILES_PUT): $(GFORTRAN_BIN_DIR)/%_put_test.exe: $(GFORTRAN_BUILD_DIR)/setter.o $(GFORTRAN_BUILD_DIR)/comparator.o $(GFORTRAN_BUILD_DIR)/generator.o $(GFORTRAN_BUILD_DIR)/helper.o $(GFORTRAN_BUILD_DIR)/%_put_test.o $(GFORTRAN_BUILD_DIR)/%_init_static.o $(GFORTRAN_BUILD_DIR)/%_init_dynamic.o $(GFORTRAN_BUILD_DIR)/%_test_static.o $(GFORTRAN_BUILD_DIR)/%_test_dynamic.o | $(GFORTRAN_BIN_DIR)
	$(FC_gfortran) $(COPTS_gfortran) -o $@ $^ $(LIBS_gfortran)	

$(GFORTRAN_BIN_FILES_GET): $(GFORTRAN_BIN_DIR)/%_get_test.exe: $(GFORTRAN_BUILD_DIR)/setter.o $(GFORTRAN_BUILD_DIR)/comparator.o $(GFORTRAN_BUILD_DIR)/generator.o $(GFORTRAN_BUILD_DIR)/helper.o $(GFORTRAN_BUILD_DIR)/%_get_test.o $(GFORTRAN_BUILD_DIR)/%_init_static.o $(GFORTRAN_BUILD_DIR)/%_init_dynamic.o $(GFORTRAN_BUILD_DIR)/%_test_static.o $(GFORTRAN_BUILD_DIR)/%_test_dynamic.o | $(GFORTRAN_BIN_DIR)
	$(FC_gfortran) $(COPTS_gfortran) -o $@ $^ $(LIBS_gfortran)

#-------------
gfortran_initpulse: initpulse.f90
	$(FC_gfortran) $(COPTS_gfortran) -o $@ $^ $(LIBS_gfortran)


#------------------------- ifort ----------------------------
.PHONY: ifort_clean
ifort_clean:
	$(RM) -r $(IFORT_BIN_DIR)
	$(RM) -r $(IFORT_BUILD_DIR)
	$(RM) ifort_initpulse
	
$(IFORT_BUILD_DIR)/generator.o: $(IFORT_BUILD_DIR)/%.o: %.f90 | $(IFORT_BUILD_DIR)
	$(FC_ifort) $(COPTS_ifort) -c $< -o $@

$(IFORT_BUILD_DIR)/helper.o \
$(IFORT_BUILD_DIR)/setter.o \
$(IFORT_BUILD_DIR)/comparator.o: $(IFORT_BUILD_DIR)/%.o: %.f90 $(IFORT_BUILD_DIR)/generator.o
	$(FC_ifort) $(COPTS_ifort) -c $< -o $@
	
$(IFORT_BUILD_DIR)/%_init_static.o: $(TEST_SRC_DIR)/%_init_static.f90 $(IFORT_BUILD_DIR)/setter.o
	$(FC_ifort) $(COPTS_ifort) -c $< -o $@
	
$(IFORT_BUILD_DIR)/%_init_dynamic.o: $(TEST_SRC_DIR)/%_init_dynamic.f90 $(IFORT_BUILD_DIR)/setter.o
	$(FC_ifort) $(COPTS_ifort) -c $< -o $@
	
$(IFORT_BUILD_DIR)/%_test_static.o: $(TEST_SRC_DIR)/%_test_static.f90 $(IFORT_BUILD_DIR)/comparator.o
	$(FC_ifort) $(COPTS_ifort) -c $< -o $@

$(IFORT_BUILD_DIR)/%_test_dynamic.o: $(TEST_SRC_DIR)/%_test_dynamic.f90 $(IFORT_BUILD_DIR)/comparator.o  
	$(FC_ifort) $(COPTS_ifort) -c $< -o $@

$(IFORT_BUILD_DIR)/%_test.o: $(TEST_SRC_DIR)/%_all_test.f90 $(IFORT_BUILD_DIR)/helper.o $(IFORT_BUILD_DIR)/%_init_static.o $(IFORT_BUILD_DIR)/%_init_dynamic.o $(IFORT_BUILD_DIR)/%_test_static.o $(IFORT_BUILD_DIR)/%_test_dynamic.o
	$(FC_ifort) $(COPTS_ifort) -c $< -o $@
	
$(IFORT_BIN_FILES): $(IFORT_BIN_DIR)/%_all_test.exe: $(IFORT_BUILD_DIR)/setter.o $(IFORT_BUILD_DIR)/comparator.o $(IFORT_BUILD_DIR)/generator.o $(IFORT_BUILD_DIR)/helper.o $(IFORT_BUILD_DIR)/%_test.o $(IFORT_BUILD_DIR)/%_init_static.o $(IFORT_BUILD_DIR)/%_init_dynamic.o $(IFORT_BUILD_DIR)/%_test_static.o $(IFORT_BUILD_DIR)/%_test_dynamic.o | $(IFORT_BIN_DIR)
	$(FC_ifort) $(COPTS_ifort) -o $@ $^ $(LIBS_ifort)

#-------------
$(IFORT_BUILD_DIR)/%_put_test.o: $(TEST_SRC_DIR)/%_put_test.f90 $(IFORT_BUILD_DIR)/helper.o $(IFORT_BUILD_DIR)/%_init_static.o $(IFORT_BUILD_DIR)/%_init_dynamic.o $(IFORT_BUILD_DIR)/%_test_static.o $(IFORT_BUILD_DIR)/%_test_dynamic.o
	$(FC_ifort) $(COPTS_ifort) -c $< -o $@

$(IFORT_BUILD_DIR)/%_get_test.o: $(TEST_SRC_DIR)/%_get_test.f90 $(IFORT_BUILD_DIR)/helper.o $(IFORT_BUILD_DIR)/%_init_static.o $(IFORT_BUILD_DIR)/%_init_dynamic.o $(IFORT_BUILD_DIR)/%_test_static.o $(IFORT_BUILD_DIR)/%_test_dynamic.o
	$(FC_ifort) $(COPTS_ifort) -c $< -o $@

$(IFORT_BIN_FILES_PUT): $(IFORT_BIN_DIR)/%_put_test.exe: $(IFORT_BUILD_DIR)/setter.o $(IFORT_BUILD_DIR)/comparator.o $(IFORT_BUILD_DIR)/generator.o $(IFORT_BUILD_DIR)/helper.o $(IFORT_BUILD_DIR)/%_put_test.o $(IFORT_BUILD_DIR)/%_init_static.o $(IFORT_BUILD_DIR)/%_init_dynamic.o $(IFORT_BUILD_DIR)/%_test_static.o $(IFORT_BUILD_DIR)/%_test_dynamic.o | $(IFORT_BIN_DIR)
	$(FC_ifort) $(COPTS_ifort) -o $@ $^ $(LIBS_ifort)

$(IFORT_BIN_FILES_GET): $(IFORT_BIN_DIR)/%_get_test.exe: $(IFORT_BUILD_DIR)/setter.o $(IFORT_BUILD_DIR)/comparator.o $(IFORT_BUILD_DIR)/generator.o $(IFORT_BUILD_DIR)/helper.o $(IFORT_BUILD_DIR)/%_get_test.o $(IFORT_BUILD_DIR)/%_init_static.o $(IFORT_BUILD_DIR)/%_init_dynamic.o $(IFORT_BUILD_DIR)/%_test_static.o $(IFORT_BUILD_DIR)/%_test_dynamic.o | $(IFORT_BIN_DIR)
	$(FC_ifort) $(COPTS_ifort) -o $@ $^ $(LIBS_ifort)
#-------------

ifort_initpulse: initpulse.f90
	$(FC_ifort) $(COPTS_ifort) -o $@ $^ $(LIBS_ifort)


#################################################
#              TEST
#################################################
.PHONY: test ifort_test gfortran_test

# Canned recipe that runs prerequisites as tests and produces TAP-like output
define run-tests
	@echo 1..$(words $^) # number of tests to be executed
	@N=1;for prog in $^ ;do \
	( $(test_ENV) ./$$prog 2>&1 | tee ./$$prog.log ) && \
	test 0 -eq $$(grep -c -i error ./$$prog.log ) && \
	echo ok $$N - $$prog passed. || echo not ok $$N - $$prog failed.\
	;done | tee $@.log
	@test 0 -eq $$(grep -c -i error $@.log) || exit 1
endef

gfortran_initpulse_test: gfortran_initpulse | $(TMP_DIR)
	$(run-tests)
gfortran_test: $(GFORTRAN_BIN_FILES) $(GFORTRAN_BIN_FILES_PUT) $(GFORTRAN_BIN_FILES_GET)| gfortran_initpulse_test
	$(run-tests)
ifort_initpulse_test: ifort_initpulse | $(TMP_DIR)
	$(run-tests)
ifort_test: $(IFORT_BIN_FILES) $(IFORT_BIN_FILES_PUT) $(IFORT_BIN_FILES_GET) | ifort_initpulse_test
	$(run-tests)

#----------------------- classpath deps ---------------------
include ../../../Makefile.classpath

