
ifeq ("yes","$(strip $(IMAS_GFORTRAN))")
FC ?= gfortran
FCFLAGS ?= -g -fdefault-real-8 -fPIC -fno-second-underscore -ffree-line-length-none -I$(AL_BUILD)/fortraninterface/include -J$(BUILD_DIR)
else ifeq ("yes","$(strip $(IMAS_IFORT))")
FC ?= ifort
FCFLAGS ?= -g -r8 -assume no2underscore -diag-disable:5462 -fPIC -I$(UAL_BUILD)/fortraninterface/include -shared-intel -module $(BUILD_DIR)
else ifeq ("yes","$(strip $(IMAS_NVFORTRAN))")
FC ?= nvfortran
FCFLAGS ?= -g -r8 -Mnosecond_underscore -fPIC -module=$(AL_BUILD)/fortraninterface/include
else ifeq ("yes","$(strip $(IMAS_NAGFOR))")
FC ?= nagfor
FCFLAGS ?= -g -free -kind=byte -r8 -PIC -I$(AL_BUILD)/fortraninterface/include
else ifeq ("yes","$(strip $(IMAS_G95))")
FC ?= g95
FCFLAGS ?= -g -r8 -ftrace=full -fPIC -fno-second-underscore -ffree-line-length-huge -I$(AL_BUILD)/fortraninterface/include
else
SOURCES_ONLY=yes
endif

LIBS  = -L$(AL_BUILD)/lowlevel -L$(AL_BUILD)/fortraninterface -lal-fortran -lal -lm



