
ifeq ("yes","$(strip $(IMAS_GFORTRAN))")
FC    = gfortran
COPTS = -g -fdefault-real-8 -fPIC -fno-second-underscore -ffree-line-length-none -I$(UAL_BUILD)/fortraninterface -J$(BUILD_DIR)
LIBS  = -L$(UAL_BUILD)/lowlevel -L$(UAL_BUILD)/fortraninterface -lal-fortran -lal -lm
endif 

ifeq ("yes","$(strip $(IMAS_IFORT))")
FC    = ifort
COPTS = -g -r8 -assume no2underscore  -fPIC -I$(UAL_BUILD)/fortraninterface -shared-intel -module $(BUILD_DIR)
LIBS  = -L$(UAL_BUILD)/lowlevel -L$(UAL_BUILD)/fortraninterface -lal-fortran -lal -lm
endif 

BIN_FILES=$(patsubst %.f90,$(BIN_DIR)/%.exe,$(notdir $(TEST_IDS_FILES)))



