
# Please do not run make on this file directly.
ifeq (1,$(words $(MAKEFILE_LIST)))
  $(error Do not run make on this file directly, use Makefile or Makefile-ext)
endif

# Require explicit target, do not assume make all
help:
	$(error Specify a target to run, e.g. make check)

# Make NEW_LOW_LEVEL=yes default
NEW_LOW_LEVEL?=yes

FORTRAN_BIN_DIR:=./bin/fortran
BUILD_DIR:=./build/fortran
TEST_SRC_DIR=./src
TMP_DIR=./tmp
FORTRAN_TESTS = fortran_initpulse_test fortran_test

ifneq ("no","$(strip $(IMAS_FORTRAN))")
  TARGETS += $(FORTRAN_BIN_FILES)
  TESTS += $(FORTRAN_TESTS)
endif
	
#------------------------- gfortran ----------------------------
#------------------------- ifort ----------------------------
ifeq ("ifort","$(strip $(FC))")
  FCFLAGS_ifort+=-module $(BUILD_DIR)
else # assume gfortran style
  FCFLAGS+=-J$(BUILD_DIR)
endif # ifort

#------------------------- fortran ----------------------------

# Get a list of IDS from IDSDEF file
IDSNAMES := $(shell sed '/<IDS name=/!d;s/.*name="\([^"]*\)".*/\1/' $(IDSDEF))
TEST_IDS_FILES = $(patsubst %,$(TEST_SRC_DIR)/%_all_tests.f90,$(IDSNAMES))
IDS_SOURCES += $(patsubst %,$(TEST_SRC_DIR)/%_all_tests.f90,$(IDSNAMES))
IDS_SOURCES += $(patsubst %,$(TEST_SRC_DIR)/%_test_routines.f90,$(IDSNAMES))
IDS_SOURCES += $(patsubst %,$(TEST_SRC_DIR)/%_test.f90,$(IDSNAMES))
IDS_SOURCES += $(patsubst %,$(TEST_SRC_DIR)/%_init.f90,$(IDSNAMES))


all: $(TARGETS)
check test: $(TESTS)
sources: $(IDS_SOURCES)

# sometimes GNU Make thinks, *.mod is modula file...
%.o : %.mod

# Create src and bin dirs as needed
$(TEST_SRC_DIR) $(BIN_DIR) $(BUILD_DIR) $(TMP_DIR):
	$(mkdir_p) $@

.PHONY: clean clean-src


clean: fortran_clean
	$(RM) -r idspath-*
	$(RM) -r *.log

clean-src: clean
	$(RM) -r $(TEST_SRC_DIR)


#################################################
#				 INIT: SOURCE GENERATION
#################################################
# Test if all generated sources are found to exist as files and
# gracefully skip generation if not needed.
ifeq ($(words $(IDS_SOURCES)), $(words $(wildcard $(IDS_SOURCES))))
$(IDS_SOURCES):
else
$(IDS_SOURCES): sources_
endif

# Target sources is reserved (used by user to build sources only)
# Need a single target to prevent parallel building:
sources_: IDSDef2TestSuite.xsl $(IDSDEF) | saxonicajar $(TEST_SRC_DIR)
	$(JAVA) net.sf.saxon.Transform newLowLevel=$(NEW_LOW_LEVEL) -t -s:$(IDSDEF) -xsl:IDSDef2TestSuite.xsl

#################################################
#			  BUILD
#################################################

#------------------------- gfortran ----------------------------
ifeq ("gfortran","$(strip $(FC))")
.PHONY: fortran_clean
endif

fortran_clean:
	$(RM) -r $(BIN_DIR)
	$(RM) -r $(BUILD_DIR)
	$(RM) fortran_initpulse
	
$(BUILD_DIR)/test_defs.o: $(BUILD_DIR)/%.o: %.f90 | $(BUILD_DIR)
	$(FC) $(FCFLAGS) -c $< -o $@

$(BUILD_DIR)/generator.o: $(BUILD_DIR)/%.o: %.f90 $(BUILD_DIR)/test_defs.o
	$(FC) $(FCFLAGS) -c $< -o $@

$(BUILD_DIR)/helper.o \
$(BUILD_DIR)/setter.o \
$(BUILD_DIR)/comparator.o: $(BUILD_DIR)/%.o: %.f90 $(BUILD_DIR)/generator.o
	$(FC) $(FCFLAGS) -c $< -o $@
	
$(BUILD_DIR)/%_init.o: $(TEST_SRC_DIR)/%_init.f90 $(BUILD_DIR)/setter.o $(BUILD_DIR)/helper.o
	$(FC) $(FCFLAGS) -c $< -o $@
	
$(BUILD_DIR)/%_test.o: $(TEST_SRC_DIR)/%_test.f90 $(BUILD_DIR)/comparator.o $(BUILD_DIR)/helper.o
	$(FC) $(FCFLAGS) -c $< -o $@


$(BUILD_DIR)/%_test_routines.o: $(TEST_SRC_DIR)/%_test_routines.f90  $(BUILD_DIR)/%_init.o $(BUILD_DIR)/%_test.o
	$(FC) $(FCFLAGS) -c $< -o $@

$(BUILD_DIR)/%_all_tests.o: $(TEST_SRC_DIR)/%_all_tests.f90 $(BUILD_DIR)/%_test_routines.o $(BUILD_DIR)/helper.o
	$(FC) $(FCFLAGS) -c $< -o $@
	
$(BIN_DIR)/%_all_tests.exe: $(BUILD_DIR)/%_all_tests.o  $(BUILD_DIR)/comparator.o  $(BUILD_DIR)/generator.o $(BUILD_DIR)/helper.o $(BUILD_DIR)/%_test_routines.o  $(BUILD_DIR)/setter.o $(BUILD_DIR)/%_init.o  $(BUILD_DIR)/%_test.o $(BUILD_DIR)/test_defs.o| $(BIN_DIR)
	$(FC) $(FCFLAGS) -o $@   $^ $(LIBS)
	
#-------------

fortran_initpulse: initpulse.f90
	$(FC) $(FCFLAGS) -o $@ $^ $(LIBS)




#################################################
#			  TEST
#################################################
.PHONY: test
.PHONY: fortran_test

# Canned recipe that runs prerequisites as tests and produces TAP-like output
define run-tests
	@( \
	echo 1..$(words $^) \# Tests: $(^F) ;\
	N=1;for prog in $^ ;do \
	 ( $(test_ENV) ./$$prog 2>&1 | tee ./$$prog.log ) && \
	 test 0 -eq $$(grep -c -i error ./$$prog.log ) && \
	 echo ok $$N - $$prog passed. || echo not ok $$N - $$prog failed. ;\
	done \
	) | tee $@.log
	@test 0 -eq $$(grep -c -i error $@.log) || exit 1
endef

fortran_initpulse_test: fortran_initpulse | $(TMP_DIR)
	$(run-tests)
# Run all tests grouped by IDS:
fortran_test: $(IDSNAMES:%=fortran_test_%) | fortran_initpulse_test
fortran_test_%: $(BIN_DIR)/%_all_tests.exe | fortran_initpulse_test
	$(run-tests)

#----------------------- classpath deps ---------------------
include ../../../Makefile.classpath
