
# Makefile.tests : include this file in Makefile or Makefile-ext

TARGETS = 

ifneq ("yes","$(strip $(SOURCES_ONLY))")
ifeq ("yes","$(strip $(IMAS_FORTRAN))")
TARGETS += $(subst .f90,,$(wildcard *serialize*.f90))
TARGETS += $(subst .f90,,$(wildcard *create*.f90))
TARGETS += $(subst .f90,,$(wildcard *put*.f90))
TARGETS += $(subst .f90,,$(wildcard *get*.f90))
TARGETS += $(subst .f90,,$(wildcard *copy*.f90))
TARGETS += $(subst .f90,,$(wildcard *memory*.f90))
TARGETS += $(subst .f90,,$(wildcard *empty*.f90))
TARGETS += $(subst .f90,,$(wildcard *validate*.f90))
TARGETS += $(subst .f90,,$(wildcard *is_defined*.f90))
TARGETS += test_version

ifneq ("","$(strip $(IMAS_AL_PLUGINS))")
	ifneq ("$(wildcard $(IMAS_AL_PLUGINS))", "")
		TARGETS += $(subst .f90,,$(wildcard *plugin*.f90))
	endif
endif
endif
endif

WILDCARD_AL_PLUGINS=$(wildcard $(IMAS_AL_PLUGINS))
$(info $$TARGETS is [${TARGETS}])
$(info $$IMAS_AL_PLUGINS Directory exists : [${WILDCARD_AL_PLUGINS}])
$(info $$IMAS_AL_PLUGINS is [${IMAS_AL_PLUGINS}])

all examples: $(TARGETS)

sources sources_install sources_uninstall install uninstall clean-src:

check test: run_tests

clean clean-ex:
	$(RM) *.o *~ $(TARGETS) $(addsuffix .log,$(TARGETS))
	$(RM) fortran_tests.log
	$(RM) -r $(TMPDIR)


test_%: test_%.f90
	$(FC) $(FCFLAGS) -o $@ $^ $(LIBS)


# Run tests
.PHONY: test run_tests 

run_tests: $(filter test_%,$(TARGETS)) | $(TMPDIR)
	@echo "Execute examples with IMAS_AL_ENABLE_PLUGINS=TRUE"
	$(if $^,$(run-tests-with-plugin))
	@echo "Execute examples with IMAS_AL_ENABLE_PLUGINS=FALSE"
	$(if $^,$(run-tests-without-plugin))


# Convenience targets for individual tests, e.g. make test_<program>
#test_%: %
#	$(run-tests-with-plugin)
#	$(run-tests-without-plugin)

$(TMPDIR):;$(mkdir_p) $@

# Canned recipe that runs prerequisites as tests and produces TAP-like output
define run-tests-with-plugin
	$(if $(DEBUG),,@)( \
	echo 1..$(words $^) \# Running $@: $(^F) ;\
	N=1;for prog in $^ ;do \
	 ( $(test_with_plugins_ENV) ./$$prog 2>&1 | tee ./$$prog.log ) && \
	 test 0 -eq $$(grep -c -i -E "fault|\<error\>|exception|severe|abort|segmentation|fault|dump" ./$$prog.log ) && \
	 echo ok $$N - $$prog passed. || echo not ok $$N - $$prog failed. ;\
	 N=$$(($$N+1)) ;\
	done \
	) | tee $@.log
	@(echo Log summary of $@ with plugins:; grep -E "^ok |^not ok " $@.log) >&2
	@test 0 -eq $$(grep -c -i -E "^not ok" $@.log) || exit 1
endef

# Canned recipe that runs prerequisites as tests and produces TAP-like output
define run-tests-without-plugin
	$(if $(DEBUG),,@)( \
	echo 1..$(words $(filter-out %_plugin, $(TARGETS))) \# Running $@: $(^F) ;\
	N=1;for prog in $(filter-out %_plugin, $(TARGETS))  ;do \
	 ( $(test_without_plugins_ENV) ./$$prog 2>&1 | tee ./$$prog.log ) && \
	 test 0 -eq $$(grep -c -i -E "fault|\<error\>|exception|severe|abort|segmentation|fault|dump" ./$$prog.log ) && \
	 echo ok $$N - $$prog passed. || echo not ok $$N - $$prog failed. ;\
	 N=$$(($$N+1)) ;\
	done \
	) | tee $@.log
	@(echo Log summary of $@ without plugins:; grep -E "^ok |^not ok " $@.log) >&2
	@test 0 -eq $$(grep -c -i -E "^not ok" $@.log) || exit 1
endef
